participants:
  - participant_id: '592567'
    base_path: 'inputs/test_dir2/20231011/01_592567/'
    output_path: 'outputs/592567/'
    sessions:
      - id: '000'
        exp_file: '592567_eye20_2023-10-11_09h19.49.520.csv'
        gaze_file: '000/exports/000/gaze_positions.csv'
        video_file: '000/world.mp4'
      - id: '001'
        exp_file: '592567_eye20_2023-10-11_09h23.19.744.csv'
        gaze_file: '001/exports/000/gaze_positions.csv'
        video_file: '001/world.mp4'

  - participant_id: '245871'
    base_path: 'inputs/test_dir2/20231011/02_245871/'
    output_path: 'outputs/245871/'
    sessions:
      - id: '002'
        exp_file: '245871_eye20_2023-10-11_10h17.30.553.csv'
        gaze_file: '002/exports/000/gaze_positions.csv'
        video_file: '002/world.mp4'
      - id: '003'
        exp_file: '245871_eye20_2023-10-11_10h21.19.193.csv'
        gaze_file: '003/exports/000/gaze_positions.csv'
        video_file: '003/world.mp4'

  - participant_id: '292304'
    base_path: 'inputs/test_dir2/20231011/03_292304/'
    output_path: 'outputs/292304/'
    sessions:
      - id: '004'
        exp_file: '292304_eye20_2023-10-11_10h55.08.090.csv'
        gaze_file: '004/exports/000/gaze_positions.csv'
        video_file: '004/world.mp4'
      - id: '005'
        exp_file: '292304_eye20_2023-10-11_10h59.09.370.csv'
        gaze_file: '005/exports/000/gaze_positions.csv'
        video_file: '005/world.mp4'

  - participant_id: '745201'
    base_path: 'inputs/test_dir2/20231011/04_745201/'
    output_path: 'outputs/745201/'
    sessions:
      - id: '006'
        exp_file: '745201_eye20_2023-10-11_12h05.01.748.csv'
        gaze_file: '006/exports/000/gaze_positions.csv'
        video_file: '006/world.mp4'
      - id: '007'
        exp_file: '745201_eye20_2023-10-11_12h09.21.435.csv'
        gaze_file: '007/exports/000/gaze_positions.csv'
        video_file: '007/world.mp4'

  - participant_id: '656713'
    base_path: 'inputs/test_dir2/20231011/05_656713/'
    output_path: 'outputs/656713/'
    sessions:
      - id: '008'
        exp_file: '656713_eye20_2023-10-11_12h35.41.213.csv'
        gaze_file: '008/exports/000/gaze_positions.csv'
        video_file: '008/world.mp4'
      - id: '009'
        exp_file: '656713_eye20_2023-10-11_12h40.08.005.csv'
        gaze_file: '009/exports/000/gaze_positions.csv'
        video_file: '009/world.mp4'

  - participant_id: '973570'
    base_path: 'inputs/test_dir2/20231011/06_973570/'
    output_path: 'outputs/973570/'
    sessions:
      - id: '011'
        exp_file: '973570_eye20_2023-10-11_13h37.31.623.csv'
        gaze_file: '011/exports/000/gaze_positions.csv'
        video_file: '011/world.mp4'
      - id: '012'
        exp_file: '973570_eye20_2023-10-11_13h43.22.824.csv'
        gaze_file: '012/exports/000/gaze_positions.csv'
        video_file: '012/world.mp4'

  - participant_id: '811097'
    base_path: 'inputs/test_dir2/20231011/07_811097/'
    output_path: 'outputs/811097/'
    sessions:
      - id: '013'
        exp_file: '811097_eye20_2023-10-11_14h01.44.575.csv'
        gaze_file: '013/exports/000/gaze_positions.csv'
        video_file: '013/world.mp4'
      - id: '014'
        exp_file: '811097_eye20_2023-10-11_14h06.04.159.csv'
        gaze_file: '014/exports/000/gaze_positions.csv'
        video_file: '014/world.mp4'

  - participant_id: '825327'
    base_path: 'inputs/test_dir2/20231011/08_825327/'
    output_path: 'outputs/825327/'
    sessions:
      - id: '015'
        exp_file: '825327_eye20_2023-10-11_14h38.37.345.csv'
        gaze_file: '015/exports/000/gaze_positions.csv'
        video_file: '015/world.mp4'
      - id: '016'
        exp_file: '825327_eye20_2023-10-11_14h43.21.112.csv'
        gaze_file: '016/exports/000/gaze_positions.csv'
        video_file: '016/world.mp4'

  - participant_id: '961283'
    base_path: 'inputs/test_dir2/20231011/09_961283/'
    output_path: 'outputs/961283/'
    sessions:
      - id: '017'
        exp_file: '961283_eye20_2023-10-11_15h36.06.801.csv'
        gaze_file: '017/exports/000/gaze_positions.csv'
        video_file: '017/world.mp4'
      - id: '018'
        exp_file: '961283_eye20_2023-10-11_15h41.57.232.csv'
        gaze_file: '018/exports/000/gaze_positions.csv'
        video_file: '018/world.mp4'

  - participant_id: '840692'
    base_path: 'inputs/test_dir2/20231011/10_840692/'
    output_path: 'outputs/840692/'
    sessions:
      - id: '019'
        exp_file: '840692_eye20_2023-10-11_16h02.22.442.csv'
        gaze_file: '019/exports/000/gaze_positions.csv'
        video_file: '019/world.mp4'
      - id: '020'
        exp_file: '840692_eye20_2023-10-11_16h06.48.930.csv'
        gaze_file: '020/exports/000/gaze_positions.csv'
        video_file: '020/world.mp4'

  - participant_id: '605510'
    base_path: 'inputs/test_dir2/20231011/11_605510/'
    output_path: 'outputs/605510/'
    sessions:
      - id: '022'
        exp_file: '605510_eye20_2023-10-11_17h48.32.995.csv'
        gaze_file: '022/exports/000/gaze_positions.csv'
        video_file: '022/world.mp4'
      - id: '023'
        exp_file: '605510_eye20_2023-10-11_17h53.04.213.csv'
        gaze_file: '023/exports/000/gaze_positions.csv'
        video_file: '023/world.mp4'

  - participant_id: '961532'
    base_path: 'inputs/test_dir2/20231018/01_961532/'
    output_path: 'outputs/961532/'
    sessions:
      - id: '000'
        exp_file: '961532_eye20_2023-10-18_09h53.23.544.csv'
        gaze_file: '000/exports/000/gaze_positions.csv'
        video_file: '000/world.mp4'
      - id: '001'
        exp_file: '961532_eye20_2023-10-18_10h01.29.529.csv'
        gaze_file: '001/exports/000/gaze_positions.csv'
        video_file: '001/world.mp4'

  - participant_id: '273108'
    base_path: 'inputs/test_dir2/20231018/02_273108/'
    output_path: 'outputs/273108/'
    sessions:
      - id: '002'
        exp_file: '273108_eye20_2023-10-18_12h29.20.867.csv'
        gaze_file: '002/exports/000/gaze_positions.csv'
        video_file: '002/world.mp4'
      - id: '003'
        exp_file: '273108_eye20_2023-10-18_12h34.11.803.csv'
        gaze_file: '003/exports/000/gaze_positions.csv'
        video_file: '003/world.mp4'

  - participant_id: '894910'
    base_path: 'inputs/test_dir2/20231018/03_894910/'
    output_path: 'outputs/894910/'
    sessions:
      - id: '004'
        exp_file: '894910_eye20_2023-10-18_13h53.36.846.csv'
        gaze_file: '004/exports/000/gaze_positions.csv'
        video_file: '004/world.mp4'
      - id: '005'
        exp_file: '894910_eye20_2023-10-18_13h58.07.829.csv'
        gaze_file: '005/exports/000/gaze_positions.csv'
        video_file: '005/world.mp4'

  - participant_id: '069956'
    base_path: 'inputs/test_dir2/20231018/04_069956/'
    output_path: 'outputs/069956/'
    sessions:
      - id: '006'
        exp_file: '069956_eye20_2023-10-18_14h35.47.389.csv'
        gaze_file: '006/exports/000/gaze_positions.csv'
        video_file: '006/world.mp4'
      - id: '007'
        exp_file: '069956_eye20_2023-10-18_14h41.44.078.csv'
        gaze_file: '007/exports/000/gaze_positions.csv'
        video_file: '007/world.mp4'

  - participant_id: '576592'
    base_path: 'inputs/test_dir2/20231018/05_576592/'
    output_path: 'outputs/576592/'
    sessions:
      - id: '008'
        exp_file: '576592_eye20_2023-10-18_15h04.15.919.csv'
        gaze_file: '008/exports/000/gaze_positions.csv'
        video_file: '008/world.mp4'
      - id: '009'
        exp_file: '576592_eye20_2023-10-18_15h10.18.223.csv'
        gaze_file: '009/exports/000/gaze_positions.csv'
        video_file: '009/world.mp4'

  - participant_id: '402438'
    base_path: 'inputs/test_dir2/20231018/06_402438/'
    output_path: 'outputs/402438/'
    sessions:
      - id: '010'
        exp_file: '402438_eye20_2023-10-18_15h39.57.894.csv'
        gaze_file: '010/exports/000/gaze_positions.csv'
        video_file: '010/world.mp4'
      - id: '011'
        exp_file: '402438_eye20_2023-10-18_15h44.49.623.csv'
        gaze_file: '011/exports/000/gaze_positions.csv'
        video_file: '011/world.mp4'

  - participant_id: '921179'
    base_path: 'inputs/test_dir2/20231018/07_921179/'
    output_path: 'outputs/921179/'
    sessions:
      - id: '012'
        exp_file: '921179_eye20_2023-10-18_16h18.51.239.csv'
        gaze_file: '012/exports/000/gaze_positions.csv'
        video_file: '012/world.mp4'
      - id: '013'
        exp_file: '921179_eye20_2023-10-18_16h24.48.049.csv'
        gaze_file: '013/exports/000/gaze_positions.csv'
        video_file: '013/world.mp4'

  - participant_id: '096306'
    base_path: 'inputs/test_dir2/20231025/01_096306/'
    output_path: 'outputs/096306/'
    sessions:
      - id: '000'
        exp_file: '096306_eye20_2023-10-25_09h12.43.235.csv'
        gaze_file: '000/exports/000/gaze_positions.csv'
        video_file: '000/world.mp4'
      - id: '001'
        exp_file: '096306_eye20_2023-10-25_09h17.19.908.csv'
        gaze_file: '001/exports/000/gaze_positions.csv'
        video_file: '001/world.mp4'

  - participant_id: '131404'
    base_path: 'inputs/test_dir2/20231025/02_131404/'
    output_path: 'outputs/131404/'
    sessions:
      - id: '002'
        exp_file: '131484_eye20_2023-10-25_09h51.21.975.csv'
        gaze_file: '002/exports/000/gaze_positions.csv'
        video_file: '002/world.mp4'
      - id: '003'
        exp_file: '131484_eye20_2023-10-25_09h56.22.845.csv'
        gaze_file: '003/exports/000/gaze_positions.csv'
        video_file: '003/world.mp4'

  - participant_id: '086516'
    base_path: 'inputs/test_dir2/20231025/03_086516/'
    output_path: 'outputs/086516/'
    sessions:
      - id: '004'
        exp_file: '086516_eye20_2023-10-25_11h06.35.337.csv'
        gaze_file: '004/exports/000/gaze_positions.csv'
        video_file: '004/world.mp4'
      - id: '005'
        exp_file: '086516_eye20_2023-10-25_11h11.45.015.csv'
        gaze_file: '005/exports/000/gaze_positions.csv'
        video_file: '005/world.mp4'

  - participant_id: '574456'
    base_path: 'inputs/test_dir2/20231025/04_574456/'
    output_path: 'outputs/574456/'
    sessions:
      - id: '006'
        exp_file: '574456_eye20_2023-10-25_12h27.54.267.csv'
        gaze_file: '006/exports/000/gaze_positions.csv'
        video_file: '006/world.mp4'
      - id: '007'
        exp_file: '574456_eye20_2023-10-25_12h33.38.609.csv'
        gaze_file: '007/exports/000/gaze_positions.csv'
        video_file: '007/world.mp4'

  - participant_id: '832037'
    base_path: 'inputs/test_dir2/20231025/05_832037/'
    output_path: 'outputs/832037/'
    sessions:
      - id: '008'
        exp_file: '832037_eye20_2023-10-25_13h09.44.553.csv'
        gaze_file: '008/exports/000/gaze_positions.csv'
        video_file: '008/world.mp4'
      - id: '009'
        exp_file: '832037_eye20_2023-10-25_13h15.13.753.csv'
        gaze_file: '009/exports/000/gaze_positions.csv'
        video_file: '009/world.mp4'

  - participant_id: '162940'
    base_path: 'inputs/test_dir2/20231025/06_162940/'
    output_path: 'outputs/162940/'
    sessions:
      - id: '010'
        exp_file: '162940_eye20_2023-10-25_15h00.24.011.csv'
        gaze_file: '010/exports/000/gaze_positions.csv'
        video_file: '010/world.mp4'
      - id: '011'
        exp_file: '162940_eye20_2023-10-25_15h05.42.740.csv'
        gaze_file: '011/exports/000/gaze_positions.csv'
        video_file: '011/world.mp4'

  - participant_id: '666992'
    base_path: 'inputs/test_dir2/20231101/01_666992/'
    output_path: 'outputs/666992/'
    sessions:
      - id: '000'
        exp_file: '666992_eye20_2023-11-01_09h45.22.155.csv'
        gaze_file: '000/exports/000/gaze_positions.csv'
        video_file: '000/world.mp4'
      - id: '001'
        exp_file: '666992_eye20_2023-11-01_09h49.55.066.csv'
        gaze_file: '001/exports/000/gaze_positions.csv'
        video_file: '001/world.mp4'

  - participant_id: '541050'
    base_path: 'inputs/test_dir2/20231101/02_541050/'
    output_path: 'outputs/541050/'
    sessions:
      - id: '002'
        exp_file: '541050_eye20_2023-11-01_11h04.48.373.csv'
        gaze_file: '002/exports/000/gaze_positions.csv'
        video_file: '002/world.mp4'
      - id: '003'
        exp_file: '541050_eye20_2023-11-01_11h08.38.131.csv'
        gaze_file: '003/exports/000/gaze_positions.csv'
        video_file: '003/world.mp4'

  - participant_id: '946679'
    base_path: 'inputs/test_dir2/20231101/03_946679/'
    output_path: 'outputs/946679/'
    sessions:
      - id: '004'
        exp_file: '946679_eye20_2023-11-01_11h47.21.660.csv'
        gaze_file: '004/exports/000/gaze_positions.csv'
        video_file: '004/world.mp4'
      - id: '005'
        exp_file: '946679_eye20_2023-11-01_11h53.33.293.csv'
        gaze_file: '005/exports/000/gaze_positions.csv'
        video_file: '005/world.mp4'

  - participant_id: '404866'
    base_path: 'inputs/test_dir2/20231101/04_404866/'
    output_path: 'outputs/404866/'
    sessions:
      - id: '006'
        exp_file: '404866_eye20_2023-11-01_13h02.20.534.csv'
        gaze_file: '006/exports/000/gaze_positions.csv'
        video_file: '006/world.mp4'
      - id: '007'
        exp_file: '404866_eye20_2023-11-01_13h06.58.829.csv'
        gaze_file: '007/exports/000/gaze_positions.csv'
        video_file: '007/world.mp4'

  - participant_id: '859224'
    base_path: 'inputs/test_dir2/20231101/05_859224/'
    output_path: 'outputs/859224/'
    sessions:
      - id: '008'
        exp_file: '859224_eye20_2023-11-01_13h42.35.815.csv'
        gaze_file: '008/exports/000/gaze_positions.csv'
        video_file: '008/world.mp4'
      - id: '009'
        exp_file: '859224_eye20_2023-11-01_13h47.28.448.csv'
        gaze_file: '009/exports/000/gaze_positions.csv'
        video_file: '009/world.mp4'

  - participant_id: '604598'
    base_path: 'inputs/test_dir2/20231101/06_604598/'
    output_path: 'outputs/604598/'
    sessions:
      - id: '010'
        exp_file: '604598_eye20_2023-11-01_15h12.45.362.csv'
        gaze_file: '010/exports/000/gaze_positions.csv'
        video_file: '010/world.mp4'
      - id: '011'
        exp_file: '604598_eye20_2023-11-01_15h17.49.801.csv'
        gaze_file: '011/exports/000/gaze_positions.csv'
        video_file: '011/world.mp4'

  - participant_id: '401069'
    base_path: 'inputs/test_dir2/20231101/07_401069/'
    output_path: 'outputs/401069/'
    sessions:
      - id: '012'
        exp_file: '401069_eye20_2023-11-01_18h34.20.190.csv'
        gaze_file: '012/exports/000/gaze_positions.csv'
        video_file: '012/world.mp4'
      - id: '013'
        exp_file: '401069_eye20_2023-11-01_18h39.42.086.csv'
        gaze_file: '013/exports/000/gaze_positions.csv'
        video_file: '013/world.mp4'
