# config/config.yaml
input_path: 'input_directory/'
output_path: 'output_directory/'
filename_exp: 'data_exp.csv'
filename_gaze: 'data_gaze.csv'
filename_position: 'merged_data.csv'
time_interval: 5.999
filename_video: 'video.mp4'